### ISSUE TITLE
List of transformers/mappers

### ISSUE THREAD

**Issue by gohossein** [ormushq/ormus#1]
Which transformers/mappers we need?

**Comment by abtinokhovat** [comment]
Observing and reading the [documentation](https://segment.com/docs/protocols/transform/#use-cases) we can initialy say that the primary transformations we can implement are are below.

- Rename an event
- Rename a property or trait
- Update a property value
- Property Transformations
- - Casing functions (lowercase, uppercase, snakecase, kebabcase, or titlecase.)
