### ISSUE TITLE
Source service requirements

### ISSUE THREAD

**Issue by j3yzz** [ormushq/ormus#2]
#### Essential Information for Transmitting Data/Events
To successfully transmit data or events, the following key pieces of information are required:

1. **User Identification:** It is imperative to identify the user involved.
2. **Page Context:** Knowing the specific page where the event occurred is crucial
3. **Event Description:** Understanding the nature of the event triggered by the user is essential.

[Segment Methods Documentation](https://segment.com/docs/getting-started/01-what-is-segment/#the-segment-methods)

---
#### Anonymous User
In situations where the user may not be authenticated, it is advisable to utilize an "anonymous ID" for the user.
We can consider the Device UUID for this situation.
[Device UUID NPM library](https://www.npmjs.com/package/device-uuid)

**Comment by AtaReversei** [comment]
The first link you have provided only lists the most important fields of the transmitted data object.
This [document page](https://university.segment.com/introduction-to-segment/324252) in `Segment University` mentions two more pieces of data which are:
- Group
- Alias

**Comment by taha-ahmadi** [comment]
The source layer is where data originates and is ingested into the system. 
It's the entry point for data collection and serves as a crucial component in the data pipeline. Developing the source layer involves integrating with various sources of data, such as websites, server libraries, mobile **SDKs**, and cloud applications, to collect data and send it to the CDP. Here are some key aspects to consider when developing the source layer:
**1. Data Collection:**

- Identify the data sources: Determine which data sources you want to collect data from. These could include websites, mobile apps, IoT devices, server applications, and more.

- Data collection methods: Implement data collection methods such as JavaScript libraries for web tracking, mobile SDKs for Android and iOS, or server-side libraries to capture data from various sources.

- Data validation: Data validation in the source layer of a CDP is crucial to ensure that the collected data is accurate, consistent, and adheres to the expected format.

- Data Deduplication: Prevent duplicate data entries by identifying and removing redundant data points based on unique identifiers, timestamps, or other criteria.

**2. Data Transformation: (Which is for the Dataplane layer)**

- Data formatting: Ensure that the data collected from different sources is properly formatted and standardized for ingestion into the CDP.

- Data Transformation: Offer data transformation capabilities to clean, reformat, or harmonize data from various sources to ensure consistency and accuracy.

- Data enrichment: You may need to enrich the data by adding additional context or metadata to make it more valuable.


Here are some features to consider for the source layer development:

1. **Data Format Validation:** We have implemented data format validation to ensure that incoming data adheres to the expected structured formats, such as JSON, XML, or other predefined schema. This helps maintain data integrity and structure.

2. **Rate Limiting and Throttling:** Rate limiting and throttling mechanisms are in place to prevent brute force attacks and excessive data submissions from single sources.

3. **Data Completeness:** We ensure that all required fields are present in the incoming data. Missing critical fields could lead to incomplete or unusable data.

4. **Data Consistency:** We perform checks for consistency within the data. This includes maintaining relationships between data elements, such as product IDs and corresponding products in the database.

5. **IP Address Validation:** We verify the integrity of IP addresses to ensure they are valid and not associated with malicious sources.


in case of entities and models that we need for our platform, we need Event model that could be something in general like this:

```Go
type Event struct {
    EventName  string                 `json:"event_name"`
    UserID     string                 `json:"user_id"`
    Properties map[string]interface{} `json:"properties"`
    Timestamp  time.Time              `json:"timestamp"`
}
```

**Comment by j3yzz** [comment]
> The source layer is where data originates and is ingested into the system. It's the entry point for data collection and serves as a crucial component in the data pipeline. Developing the source layer involves integrating with various sources of data, such as websites, server libraries, mobile **SDKs**, and cloud applications, to collect data and send it to the CDP. Here are some key aspects to consider when developing the source layer: **1. Data Collection:**
> 
>     * Identify the data sources: Determine which data sources you want to collect data from. These could include websites, mobile apps, IoT devices, server applications, and more.
> 
>     * Data collection methods: Implement data collection methods such as JavaScript libraries for web tracking, mobile SDKs for Android and iOS, or server-side libraries to capture data from various sources.
> 
>     * Data validation: Data validation in the source layer of a CDP is crucial to ensure that the collected data is accurate, consistent, and adheres to the expected format.
> 
>     * Data Deduplication: Prevent duplicate data entries by identifying and removing redundant data points based on unique identifiers, timestamps, or other criteria.
> 
> 
> **2. Data Transformation: (Which is for the Dataplane layer)**
> 
>     * Data formatting: Ensure that the data collected from different sources is properly formatted and standardized for ingestion into the CDP.
> 
>     * Data Transformation: Offer data transformation capabilities to clean, reformat, or harmonize data from various sources to ensure consistency and accuracy.
> 
>     * Data enrichment: You may need to enrich the data by adding additional context or metadata to make it more valuable.
> 
> 
> Here are some features to consider for the source layer development:
> 
>     1. **Data Format Validation:** We have implemented data format validation to ensure that incoming data adheres to the expected structured formats, such as JSON, XML, or other predefined schema. This helps maintain data integrity and structure.
> 
>     2. **Rate Limiting and Throttling:** Rate limiting and throttling mechanisms are in place to prevent brute force attacks and excessive data submissions from single sources.
> 
>     3. **Data Completeness:** We ensure that all required fields are present in the incoming data. Missing critical fields could lead to incomplete or unusable data.
> 
>     4. **Data Consistency:** We perform checks for consistency within the data. This includes maintaining relationships between data elements, such as product IDs and corresponding products in the database.
> 
>     5. **IP Address Validation:** We verify the integrity of IP addresses to ensure they are valid and not associated with malicious sources.
> 
> 
> in case of entities and models that we need for our platform, we need Event model that could be something in general like this:
> 
> ```go
> type Event struct {
>     EventName  string                 `json:"event_name"`
>     UserID     string                 `json:"user_id"`
>     Properties map[string]interface{} `json:"properties"`
>     Timestamp  time.Time              `json:"timestamp"`
> }
> ```

Great idea, Taha John!

I think that by combining the Event name, user ID, and timestamp, we can effectively validate each request to identify duplicate data.

**Comment by Mdhesari** [comment]
Hello everyone,

I appreciate your thorough and valuable research. I would like to introduce another topic that also requires our attention.

Data Security and Compliance:

We should consider implementing an additional strategy for data encryption and protection. However, this is just a preliminary idea. Please share your feedback and thoughts on this matter.

@taha-ahmadi @AtaReversei @j3yzz

**Comment by taha-ahmadi** [comment]
> Hello everyone,
> 
> I appreciate your thorough and valuable research. I would like to introduce another topic that also requires our attention.
> 
> Data Security and Compliance:
> 
> We should consider implementing an additional strategy for data encryption and protection. However, this is just a preliminary idea. Please share your feedback and thoughts on this matter.
> 
> @taha-ahmadi @AtaReversei @j3yzz

Implementing additional data encryption and protection is a commendable idea. It's crucial for safeguarding sensitive data. I suggest further exploring encryption methods and compliance with industry standards. Assess the potential impact on performance and user experience to strike the right balance. Continuous improvement in this area is essential.
