### ISSUE TITLE
Event Entity/Model

### ISSUE THREAD

**Issue by abtinokhovat** [ormushq/ormus#3]
The event is the core of the CDP system. We should model it carefully. Event should be compatible with Segment.com. The Segment documentation or even JS-SDK/GO-SDK might be helpful.

**Comment by abtinokhovat** [comment]
Wandering around the [documentation](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#getting-started) we end up seeing this function being called

```
analytics.track(event,properties,options,callback)
```

the `event` field is required, and other arguments are optional we can start with implementing the `event` and `properties` arguments.

![image](https://github.com/gocasts-bootcamp/ormus/assets/76223666/040dcfac-576c-4bbf-9e8a-647211375e9f)

**Comment by AtaReversei** [comment]
I think we should start by studying the default and semantic events of `Segment` itself at [semantic events](https://segment.com/docs/connections/spec/semantic/). It provides various examples for different environments.

**Comment by gohossein** [comment]
> I think we should start by studying the default and semantic events of `Segment` itself in [semantic events](https://segment.com/docs/connections/spec/semantic/). It provides various examples for different environments.

@abtinokhovat This is an important task for your team(data plane).
