### ISSUE TITLE
Segment - Recon and discovery

### ISSUE THREAD

**Issue by abtinokhovat** [ormushq/ormus#6]
Go Application Source
---

I have tested the segment service with the go SDK provided [here](https://segment.com/docs/connections/sources/catalog/libraries/server/go/).
I have tested three function: `analytics.Identify`,  `analytics.Page`, `analytics.Track`.

---
### Identify
You can provide a `UserId` for user and then assign different `traits` to the user, like, name,  email or any key-value pair.

`Request`
```go
client.Enqueue(analytics.Identify{
    UserId: "abtinokhovat",
    Traits: analytics.NewTraits().
        SetName("Abtin Okhovat").
        SetEmail("abtin@example.com").
        Set("plan", "Enterprise").
        Set("friends", 142).
        SetGender("Male").
        SetDescription("This is a test desc"),
})
```
`Segment Raw data (Dashboard)`
```json
{
  "context": {
    "library": {
      "name": "analytics-go",
      "version": "3.0.0"
    }
  },
  "integrations": {},
  "messageId": "156bcd23-6d73-4fb2-ae51-84eabdaf130f",
  "originalTimestamp": "2023-10-31T11:53:03.061412+03:30",
  "receivedAt": "2023-10-31T08:23:12.873Z",
  "sentAt": "2023-10-31T08:23:08.062Z",
  "timestamp": "2023-10-31T08:23:07.872Z",
  "traits": {
    "description": "This is a test desc",
    "email": "abtin@example.com",
    "friends": 142,
    "gender": "Male",
    "name": "Abtin Okhovat",
    "plan": "Enterprise"
  },
  "type": "identify",
  "userId": "abtinokhovat",
  "writeKey": "REDACTED"
}
```

- 💡 When identifying user with pre-identified UserId only `messageId`, `originalTimestamp`, `receivedAt`, `sentAt`, and `timestamp` will be distinct for conspicuous reason.
---
### Track

In track function we have to add an `Event` name, and a `UserId`, and we can add extra key-value pairs in the Properties field.

`Request`
```go
client.Enqueue(analytics.Track{
    Event:  "Article Bookmarked",
    UserId: "abtinokhovat",
    Properties: analytics.NewProperties().
            Set("title", "Snow Fall").
            Set("subtitle", "The Avalanche at Tunnel Creek").
            Set("author", "John Branch"),
})
```

`Segment Raw Data (Dashboard)`

```json
{
  "context": {
    "library": {
      "name": "analytics-go",
      "version": "3.0.0"
    }
  },
  "event": "Article Bookmarked",
  "integrations": {},
  "messageId": "51672282-c097-454f-8de9-d00e0a43016f",
  "originalTimestamp": "2023-10-31T11:53:29.905488+03:30",
  "properties": {
    "author": "John Branch",
    "subtitle": "The Avalanche at Tunnel Creek",
    "title": "Snow Fall"
  },
  "receivedAt": "2023-10-31T08:23:38.069Z",
  "sentAt": "2023-10-31T08:23:34.906Z",
  "timestamp": "2023-10-31T08:23:33.067Z",
  "type": "track",
  "userId": "abtinokhovat",
  "writeKey": "REDACTED"
}
```

- 💡 If you don't send the `UserId` the event will not land the dashboard.
- 💡 If you send a `UserId` which is not `Identified` it will land dashboard but will have a title of `Unknown user`.

---
### Page
Page function will track the page views of an application, you can config the function to have multiple hosts like, `mobile`,`web page 1`, `web page 2`, or ... .

`Request`

```go
client.Enqueue(analytics.Page{
    UserId: "abtinokhovat",
    Name:   "Go Library",
    Properties: analytics.NewProperties().
        SetURL("https://segment.com/libraries/go/"),
})
```

`Segment Raw Data (Dashboard)`
```json
{
  "context": {
    "library": {
      "name": "analytics-go",
      "version": "3.0.0"
    }
  },
  "integrations": {},
  "messageId": "2b34b1f5-791e-49b3-a000-783b379e60a1",
  "name": "Go Library",
  "originalTimestamp": "2023-10-31T11:55:39.910113+03:30",
  "properties": {
    "url": "https://segment.com/libraries/go/"
  },
  "receivedAt": "2023-10-31T08:25:50.863Z",
  "sentAt": "2023-10-31T08:25:44.911Z",
  "timestamp": "2023-10-31T08:25:45.862Z",
  "type": "page",
  "userId": "abtinokhovat",
  "writeKey": "REDACTED"
}
```
---

**Comment by abtinokhovat** [comment]
- Further investigation for other SDKs is needed, for founding any difference.
- I will setup a PostgresDB instance as a destination, and will update this issue if found any new information.

**Comment by gohossein** [comment]
> * Further investigation for other SDKs is needed, for founding any difference.
> * I will setup a PostgresDB instance as a destination, and will update this issue if found any new information.

Great Abtin jan, I have a question, is it necessary for the client to send the `Identify` message before any other message?

**Comment by DOO-DEV** [comment]
> * Further investigation for other SDKs is needed, for founding any difference.
> * I will setup a PostgresDB instance as a destination, and will update this issue if found any new information.

![image](https://github.com/ormushq/ormus/assets/96613482/87e9356b-516f-4716-855d-64080e601139)
💡 Semgment create a table for each event that we define(e.g get_profile).
💡 In this image we see the result of track "get_profile" event. result of run this code in client:
```go
	segment.SegmentClient.Enqueue(analytics.Track{
		Type:   "track",
		Event:  "Get Profile",
		UserId: claims.ID,
	})
```
<hr/>

![image](https://github.com/ormushq/ormus/assets/96613482/b05426b8-69a5-4b2f-aa83-fafc79882730)
💡 Segment although create a table for each main functionality(track, page, identify, group...)

<hr/>

![image](https://github.com/ormushq/ormus/assets/96613482/75e2997c-e6e8-4f7b-ad4c-82cf67ff7d05)
💡 Users table also created

**Comment by gohossein** [comment]
> > * Further investigation for other SDKs is needed, for founding any difference.
> > * I will setup a PostgresDB instance as a destination, and will update this issue if found any new information.
> 
> ![image](https://user-images.githubusercontent.com/96613482/280296662-87e9356b-516f-4716-855d-64080e601139.png) 💡 Semgment create a table for each event that we define(e.g get_profile). 💡 In this image we see the result of track "get_profile" event. result of run this code in client:
> 
> ```go
> 	segment.SegmentClient.Enqueue(analytics.Track{
> 		Type:   "track",
> 		Event:  "Get Profile",
> 		UserId: claims.ID,
> 	})
> ```
> 
> ![image](https://user-images.githubusercontent.com/96613482/280299086-b05426b8-69a5-4b2f-aa83-fafc79882730.png) 💡 Segment although create a table for each main functionality(track, page, identify, group...)
> 
> ![image](https://user-images.githubusercontent.com/96613482/280300209-75e2997c-e6e8-4f7b-ad4c-82cf67ff7d05.png) 💡 Users table also created

Thanks @DOO-DEV jan.
