### ISSUE TITLE
#core(manager) - get list of integrations by source ID

### ISSUE THREAD

**Issue by PouriaSeyfi** [ormushq/ormus#60]
To handle destinations effectively, it is recommended to retrieve the list of integrations for a specific source by making HTTP/gRPC calls. This approach allows for reading different configurations and types from the integrations.

Relying solely on the event message to obtain this information may not be ideal. Including all of this data in the brokers could lead to unnecessary information and potentially impact performance negatively.

**Comment by iam-benyamin** [comment]
since we have issue 35 I will close this one!
