### ISSUE TITLE
Some changes in main function(destination)

### ISSUE THREAD

**Issue by mohsenHa** [ormushq/ormus#75]
Upon reviewing the main function at line 90, I observed the instantiation of a new task coordinator and the creation of task managers such as webhook within the creation function.

In my opinion, it would enhance clarity to register task managers in the main function after initializing the task coordinator, but before commencing its operation. This approach can provide a clearer understanding of the process flow.

Considering the current difficulty in comprehending the code structure, I suggest refactoring the main function for improved code readability. This adjustment is necessary as the complexity of the code makes it challenging to grasp its functionality at a glance.

@iam-benyamin 
@gohossein 
@PouriaSeyfi

**Comment by PouriaSeyfi** [comment]
Thank you @mohsenHa  for your suggestion. 
This is considerable, but I think task managers can be very various depend on nature of coordinator. 
for example destination type coordinator can have multiple task managers base on type of destination types that can be handled. 

so at this level, I found that there is a complex and  maybe unique business logic to understand which task manager should be used for each coordinator.
